name: Deploy-CoOperativeBank-Build

on: 

  workflow_dispatch:

     inputs:
       coditech_build:
         description: 'Build Coditech'
         required: true
         default: true
         type: boolean
       admin_deploy:
         description: 'Deploy Admin'
         required: true
         default: true
         type: boolean
       mediamanager_api_deploy:
         description: 'Deploy MediaManager API'
         required: true
         default: true
         type: boolean
       organisation_api_deploy:
         description: 'Deploy Organisation API'
         required: true
         default: true
         type: boolean
       cooperativebank_api_deploy:
         description: 'Deploy CoOperativeBank API'
         required: true
         default: true
         type: boolean
       payment_api_deploy:
         description: 'Deploy Payment API'
         required: true
         default: true
         type: boolean

jobs:
  coditech_build:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    if: github.event.inputs.coditech_build == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Restore Packages
        run: | 
           & "C:\\GitAction\\nugettools\\nuget.exe" restore './Coditech.Project/Coditech.Project.sln' -DirectDownload -MSBuildPath "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\"

      - name: Build
        run: | 
           & "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\msbuild.exe"  './Coditech.Project/Coditech.Project.sln' /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="./publish/Release" /p:Configuration=Release /p:TransformConfigFiles=false

  admin_deploy:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    needs: coditech_build
    if: github.event.inputs.admin_deploy == 'true'
    
    steps:
      - name: Stop ADMIN IIS Site and App Pool
        run: |
          # Stop the IIS site
          Stop-WebSite -Name "cooperativebank-stage-admin" 

          # Stop the associated app pool
          Stop-WebAppPool -Name "cooperativebank-stage-admin"

          # Wait for a few seconds (optional, if needed)
          Start-Sleep -Seconds 5

      - name: Copy Build file
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\Admin\Coditech.Admin\bin\Release\net8.0\*  -Destination C:\HostingSites\CoOperativeBank\Admin\ -Recurse -Force
      - name: Copy Build webroot
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\Admin\Coditech.Admin\wwwroot\*  -Destination C:\HostingSites\CoOperativeBank\Admin\wwwroot\ -Recurse -Force
      - name: Copy Build views
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\Admin\Coditech.Admin\Views\*  -Destination C:\HostingSites\CoOperativeBank\Admin\Views\ -Recurse -Force
      - name: Copy Build report folder
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\Admin\Coditech.Admin\Reports\*  -Destination C:\HostingSites\CoOperativeBank\Admin\Reports\ -Recurse -Force

      - name: Start ADMIN IIS Site and App Pool
        run: |
          # Start the IIS site
          Start-WebSite -Name "cooperativebank-stage-admin"

          # Start the associated app pool
          Start-WebAppPool -Name "cooperativebank-stage-admin"

  mediamanager_api_deploy:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    needs: coditech_build
    if: github.event.inputs.mediamanager_api_deploy == 'true'

    steps:

      - name: Stop MediaManager IIS Site and App Pool
        run: |
           # Stop the IIS site
           Stop-WebSite -Name "cooperativebank-stage-api-mediamanager" 
           # Stop the associated app pool
           Stop-WebAppPool -Name "cooperativebank-stage-api-mediamanager"

           # Wait for a few seconds (optional, if needed)
           Start-Sleep -Seconds 5

      - name: Copy Build file
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\API\Coditech.Engine.MediaManager\bin\Release\net8.0\* -Destination C:\HostingSites\CoOperativeBank\MediaManager\ -Recurse -Force 

      - name: Start MediaManager IIS Site and App Pool
        run: |
           # Start the IIS site
           Start-WebSite -Name "cooperativebank-stage-api-mediamanager"
           # Start the associated app pool
           Start-WebAppPool -Name "cooperativebank-stage-api-mediamanager"

  organisation_api_deploy:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    needs: coditech_build
    if: github.event.inputs.organisation_api_deploy == 'true'

    steps:
      - name: Stop Organisation IIS Site and App Pool
        run: |
           # Stop the IIS site
           Stop-WebSite -Name "cooperativebank-stage-api-organisation" 
           # Stop the associated app pool
           Stop-WebAppPool -Name "cooperativebank-stage-organisation"

           # Wait for a few seconds (optional, if needed)
           Start-Sleep -Seconds 5

      - name: Copy Build file
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\API\Coditech.Engine.Organisation\bin\Release\net8.0\* -Destination C:\HostingSites\CoOperativeBank\Organisation\ -Recurse -Force 

      - name: Start Organisation IIS Site and App Pool
        run: |
           # Start the IIS site
           Start-WebSite -Name "cooperativebank-stage-api-organisation"
           # Start the associated app pool
           Start-WebAppPool -Name "cooperativebank-stage-api-organisation"
           
  cooperativebank_api_deploy:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    needs: coditech_build
    if: github.event.inputs.cooperativebank_api_deploy == 'true'

    steps:
      - name: Stop cooperativebank IIS Site and App Pool
        run: |
           # Stop the IIS site
           Stop-WebSite -Name "cooperativebank-stage-api-cooperativebank" 
           # Stop the associated app pool
           Stop-WebAppPool -Name "cooperativebank-stage-api-cooperativebank"

           # Wait for a few seconds (optional, if needed)
           Start-Sleep -Seconds 5

      - name: Copy Build file
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\API\Coditech.Engine.CoOperativeBank\bin\Release\net8.0\* -Destination C:\HostingSites\CoOperativeBank\CoOperativeBank\ -Recurse -Force 

      - name: Start cooperativebank IIS Site and App Pool
        run: |
           # Start the IIS site
           Start-WebSite -Name "cooperativebank-stage-api-cooperativebank"
           # Start the associated app pool
           Start-WebAppPool -Name "cooperativebank-stage-api-cooperativebank"

  payment_api_deploy:
    runs-on: [self-hosted, Windows, x64, cooperativebank_stage]
    needs: coditech_build
    if: github.event.inputs.payment_api_deploy == 'true'

    steps:
      - name: Stop payment IIS Site and App Pool
        run: |
           # Stop the IIS site
           Stop-WebSite -Name "cooperativebank-stage-api-payment" 
           # Stop the associated app pool
           Stop-WebAppPool -Name "cooperativebank-stage-api-payment"

           # Wait for a few seconds (optional, if needed)
           Start-Sleep -Seconds 5

      - name: Copy Build file
        run: Copy-Item -Path C:\GitAction\CoOperativeBank\_work\CoditechCo-OperativeBank\CoditechCo-OperativeBank\Coditech.Project\API\Coditech.Engine.Payment\bin\Release\net8.0\* -Destination C:\HostingSites\CoOperativeBank\payment\ -Recurse -Force 

      - name: Start payment IIS Site and App Pool
        run: |
           # Start the IIS site
           Start-WebSite -Name "cooperativebank-stage-api-payment"
           # Start the associated app pool
           Start-WebAppPool -Name "cooperativebank-stage-api-payment"